# Copyright 2021 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: github.com/docker/cli
        update-types: semver-major
      - dependency-name: github.com/docker/docker
        update-types: semver-major

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
