# Copyright 2021 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - mirror
    - misspell
    - musttag
    - nestif
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - reassign
    - staticcheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: k8s.io/kubernetes
              desc: do not use k8s.io/kubernetes directly
            - pkg: github.com/minio
              desc: dependencies on minio libraries are not allowed
    errcheck:
      exclude-functions:
        - encoding/json.Marshal
        - encoding/json.MarshalIndent
    errchkjson:
      check-error-free-encoding: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gomoddirectives:
      replace-local: true
      replace-allow-list:
        - github.com/mholt/archives
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: test/*
      - linters:
          - errcheck
        source: flags.Parse|response.WriteError
      - linters:
          - gocritic
        path: docker/registry/registry.go
        text: 'hugeParam: c is heavy'
      - linters:
          - gocritic
        path: docker/registry/registry.go
        text: 'hugeParam: cfg is heavy'
    paths:
      - third_party/
formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/mesosphere)
        - Prefix(github.com/mesosphere/mindthegap)
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120
  exclusions:
    generated: lax
    paths:
      - third_party/
