# Copyright 2021 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - mirror
    - misspell
    - musttag
    - nestif
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - reassign
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: k8s.io/kubernetes
            desc: "do not use k8s.io/kubernetes directly"
  errcheck:
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  errchkjson:
    check-error-free-encoding: true
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/mesosphere)
      - Prefix(github.com/mesosphere/mindthegap)
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofumpt:
    extra-rules: true
  lll:
    line-length: 120

issues:
  exclude-rules:
    # ignore errcheck for code under a /test folder
    - path: "test/*"
      linters:
        - errcheck
    # ignore errcheck for flags.Parse (it is expected that we flag.ExitOnError)
    # ignore response.WriteError as it always returns the err it was passed
    - source: "flags.Parse|response.WriteError"
      linters:
        - errcheck
