# Copyright 2021 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 2

project_name: mindthegap

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^build:'

release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/mesosphere/mindthegap/compare/{{ .PreviousTag }}...{{ .Tag }}

builds:
  - id: mindthegap
    main: ./cmd/mindthegap
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.commitDate={{ .CommitDate }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitCommit={{ .FullCommit }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitTreeState={{ .Env.GIT_TREE_STATE }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitVersion=v{{ trimprefix .Version "v" }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.major={{ .Major }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.minor={{ .Minor }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - |
          sh -ec 'if [ {{ .IsSnapshot }} == true ] && [ {{ .Runtime.Goarch }} == {{ .Arch }} ]; then
            env SOURCE_DATE_EPOCH=$(date +%s) \
                KO_DATA_DATE_EPOCH=$(date +%s) \
                KO_DOCKER_REPO=ko.local/mindthegap \
                ko build \
                  --bare \
                  --platform linux/{{ .Arch }} \
                  -t v{{ trimprefix .Version "v" }}-{{ .Arch }} \
                  ./cmd/mindthegap
          fi'
  - id: wait-for-file-to-exist
    dir: ./cmd/wait-for-file-to-exist
    binary: wait-for-file-to-exist
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - |
          sh -ec 'if [ {{ .IsSnapshot }} == true ] && [ {{ .Runtime.Goarch }} == {{ .Arch }} ]; then
            cd ./cmd/wait-for-file-to-exist && \
              env SOURCE_DATE_EPOCH=$(date +%s) \
                  KO_DATA_DATE_EPOCH=$(date +%s) \
                  KO_DOCKER_REPO=ko.local/wait-for-file-to-exist \
                  KO_DEFAULTBASEIMAGE=cgr.dev/chainguard/busybox \
                  ko build \
                    --bare \
                    --platform linux/{{ .Arch }} \
                    -t v{{ trimprefix .Version "v" }}-{{ .Arch }} \
                    .
          fi'
  - id: copy-file-to-pod
    dir: ./cmd/copy-file-to-pod
    binary: copy-file-to-pod
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - |
          sh -ec 'if [ {{ .IsSnapshot }} == true ] && [ {{ .Runtime.Goarch }} == {{ .Arch }} ]; then
            cd ./cmd/copy-file-to-pod && \
              env SOURCE_DATE_EPOCH=$(date +%s) \
                  KO_DATA_DATE_EPOCH=$(date +%s) \
                  KO_DOCKER_REPO=ko.local/copy-file-to-pod \
                  ko build \
                    --bare \
                    --platform linux/{{ .Arch }} \
                    -t v{{ trimprefix .Version "v" }}-{{ .Arch }} \
                    .
          fi'

upx:
  - enabled: "{{ not .IsSnapshot }}"
    goos:
      - linux
    compress: "9"
    lzma: true
  - enabled: "{{ not .IsSnapshot }}"
    goos:
      - windows
    goarch:
      - amd64
    compress: "9"
    lzma: true

archives:
  - name_template: '{{ .ProjectName }}_v{{trimprefix .Version "v"}}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - mindthegap
      - wait-for-file-to-exist
      - copy-file-to-pod

kos:
  - id: mindthegap
    build: mindthegap
    labels:
      org.opencontainers.image.created: "{{ .CommitDate }}"
      org.opencontainers.image.title: mindthegap
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: v{{trimprefix .Version "v"}}
      org.opencontainers.image.source: "{{ .GitURL }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repository: ghcr.io/mesosphere/mindthegap
    bare: true
    tags:
      - v{{trimprefix .Version "v"}}
  - id: wait-for-file-to-exist
    build: wait-for-file-to-exist
    labels:
      org.opencontainers.image.created: "{{ .CommitDate }}"
      org.opencontainers.image.title: wait-for-file-to-exist
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: v{{trimprefix .Version "v"}}
      org.opencontainers.image.source: "{{ .GitURL }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repository: ghcr.io/mesosphere/wait-for-file-to-exist
    base_image: cgr.dev/chainguard/busybox
    bare: true
    tags:
      - v{{trimprefix .Version "v"}}
  - id: copy-file-to-pod
    build: copy-file-to-pod
    labels:
      org.opencontainers.image.created: "{{ .CommitDate }}"
      org.opencontainers.image.title: copy-file-to-pod
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: v{{trimprefix .Version "v"}}
      org.opencontainers.image.source: "{{ .GitURL }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repository: ghcr.io/mesosphere/copy-file-to-pod
    bare: true
    tags:
      - v{{trimprefix .Version "v"}}

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incminor .Tag }}-dev"
report_sizes: true
