# Copyright 2021 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 2

project_name: mindthegap

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^build:'

release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/mesosphere/mindthegap/compare/{{ .PreviousTag }}...{{ .Tag }}

builds:
  - dir: ./cmd/mindthegap
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.commitDate={{ .CommitDate }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitCommit={{ .FullCommit }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitTreeState={{ .Env.GIT_TREE_STATE }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitVersion=v{{ trimprefix .Version "v" }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.major={{ .Major }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.minor={{ .Minor }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

upx:
  - enabled: "{{ not .IsSnapshot }}"
    goos:
      - linux
    compress: "9"
    lzma: true
  - enabled: "{{ not .IsSnapshot }}"
    goos:
      - windows
    goarch:
      - amd64
    compress: "9"
    lzma: true

archives:
  - format_overrides:
      - goos: windows
        format: zip

kos:
  - labels:
      org.opencontainers.image.created: "{{ .CommitDate }}"
      org.opencontainers.image.title: mindthegap
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: v{{trimprefix .Version "v"}}
      org.opencontainers.image.source: "{{ .GitURL }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repository: ghcr.io/mesosphere/mindthegap
    bare: true
    tags:
      - v{{trimprefix .Version "v"}}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incminor .Tag }}-dev"
report_sizes: true
