# Copyright 2021 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 2

project_name: mindthegap

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^build:'

release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/mesosphere/mindthegap/compare/{{ .PreviousTag }}...{{ .Tag }}

builds:
  - id: mindthegap
    main: ./cmd/mindthegap
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.commitDate={{ .CommitDate }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitCommit={{ .FullCommit }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitTreeState={{ .Env.GIT_TREE_STATE }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.gitVersion=v{{ trimprefix .Version "v" }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.major={{ .Major }}'
      - -X 'github.com/mesosphere/dkp-cli-runtime/core/cmd/version.minor={{ .Minor }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
  - id: wait-for-files-to-exist
    dir: ./cmd/wait-for-files-to-exist
    binary: wait-for-files-to-exist
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
  - id: copy-file-to-pod
    dir: ./cmd/copy-file-to-pod
    binary: copy-file-to-pod
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

upx:
  - enabled: "{{ not .IsSnapshot }}"
    goos:
      - linux
    compress: "9"
    lzma: true
  - enabled: "{{ not .IsSnapshot }}"
    goos:
      - windows
    goarch:
      - amd64
    compress: "9"
    lzma: true

archives:
  - name_template: '{{ .ProjectName }}_v{{trimprefix .Version "v"}}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    ids:
      - mindthegap
      - wait-for-files-to-exist
      - copy-file-to-pod

kos:
  - id: mindthegap
    build: mindthegap
    labels:
      org.opencontainers.image.created: "{{ .CommitDate }}"
      org.opencontainers.image.title: mindthegap
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: v{{trimprefix .Version "v"}}
      org.opencontainers.image.source: "{{ .GitURL }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repositories:
      - ghcr.io/mesosphere/mindthegap
    bare: true
    tags:
      - v{{trimprefix .Version "v"}}
  - id: wait-for-files-to-exist
    build: wait-for-files-to-exist
    labels:
      org.opencontainers.image.created: "{{ .CommitDate }}"
      org.opencontainers.image.title: wait-for-files-to-exist
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: v{{trimprefix .Version "v"}}
      org.opencontainers.image.source: "{{ .GitURL }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repositories:
      - ghcr.io/mesosphere/wait-for-files-to-exist
    base_image: cgr.dev/chainguard/busybox
    bare: true
    tags:
      - v{{trimprefix .Version "v"}}
  - id: copy-file-to-pod
    build: copy-file-to-pod
    labels:
      org.opencontainers.image.created: "{{ .CommitDate }}"
      org.opencontainers.image.title: copy-file-to-pod
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: v{{trimprefix .Version "v"}}
      org.opencontainers.image.source: "{{ .GitURL }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repositories:
      - ghcr.io/mesosphere/copy-file-to-pod
    bare: true
    tags:
      - v{{trimprefix .Version "v"}}

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incminor .Tag }}-dev"
report_sizes: true
