# Copyright 2021 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

exclude: ^third_party/.*$

repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: local
  hooks:
  - id: update-mholt-archives-fork
    name: Update mholt/archives fork
    stages: [pre-commit]
    entry: task fork-archives:update
    language: system
    types_or:
      - go-mod
      - go-sum
    pass_filenames: false
  - id: go-mod-tidy
    name: go mod tidy
    stages: [pre-commit]
    entry: task go:mod-tidy
    language: system
    types_or:
      - go-mod
      - go-sum
      - go
    pass_filenames: false
  - id: golangci-lint
    name: golangci-lint
    stages: [pre-commit]
    entry: task go:lint
    language: system
    types: [go]
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    stages: [pre-commit]
  - id: check-yaml
    args: ["-m", "--unsafe"]
    stages: [pre-commit]
  - id: mixed-line-ending
    args: ["-f", "lf"]
    stages: [pre-commit]
  - id: no-commit-to-branch
    stages: [pre-commit]
  - id: check-added-large-files
    stages: [pre-commit]
  - id: check-case-conflict
    stages: [pre-commit]
  - id: check-merge-conflict
    stages: [pre-commit]
  - id: check-executables-have-shebangs
    stages: [pre-commit]
  - id: end-of-file-fixer
    stages: [pre-commit]
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint-system
    stages: [pre-commit]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
  - id: gitlint-ci
    args: ["--commits", "origin/main..HEAD"]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shfmt
    stages: [pre-commit]
    args: ["-s", "-i", "2"]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
    stages: [pre-commit]
    args: ["-e", "SC2211"]
    exclude: ^\.envrc$
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.44.0
  hooks:
  - id: markdownlint
    stages: [pre-commit]
    exclude: ^CHANGELOG.md$
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: insert-license
    name: License headers - Go
    stages: [pre-commit]
    files: "(.*\\.go|go.mod)$"
    args:
      - --license-filepath
      - header.txt
      - --comment-style
      - //
      - --allow-past-years
  - id: insert-license
    name: License headers - YAML
    stages: [pre-commit]
    files: \.ya?ml$
    args:
      - --license-filepath
      - header.txt
      - --allow-past-years
  - id: insert-license
    name: License headers - Markdown
    stages: [pre-commit]
    files: \.md$
    exclude: ^CHANGELOG.md$
    args:
      - --license-filepath
      - header.txt
      - --comment-style
      - <!--|| -->
      - --allow-past-years
