# Copyright 2024 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: '3'

tasks:
  run:
    desc: Runs prek on all files
    cmds:
      - prek prepare-hooks
      - prek run -a --show-diff-on-failure
