# Copyright 2021-2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

on: workflow_dispatch
jobs:
  openssl:
    name: Recover Secret With OpenSSL
    runs-on: ubuntu-22.04
    steps:
      - env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          OPENSSL_PASSWORD: ${{ secrets.OPENSSL_PASSWORD }}
          OPENSSL_ITER: ${{ secrets.OPENSSL_ITER }}
        run: |
          echo "$(echo "${DOCKER_PASSWORD}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE_HERE | openssl base64 -d | openssl enc -d -pbkdf2 -iter \$OPENSSL_ITER -aes-256-cbc -k \$OPENSSL_PASSWORD"
